print ("========== INI PROGRAM SEDERHANA ==========")
print ("Masukan Angka yang ingin di pangkatkan:")
a = int(input(">> "))
print ("")
print ("Angka anda telah di pangkat kan 7! anda mendapat angka : ",a*a*a*a*a*a*a)
